[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28.0"
egui_extras = { version = "0.28.0", features = ["all_loaders"] }
regex = "1.10.5"
